version: '3.8'

services:
  app:
    build:
      context: ./app
    ports:
      - "5000:5000"
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.30
    ports:
      - "5775:5775"
      - "6831:6831/udp"
      - "16686:16686"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    networks:
      - jaeger-network

networks:
  jaeger-network:
    driver: bridge